version: '3.9'

services:
  postgres:
    image: postgres
    container_name: entratix_db
    environment:
      POSTGRES_DB: entratix_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: entratix_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "5050:80"
    networks:
      - mynetwork

networks:
  mynetwork:
